TREEWIDE: Fix compilation error due to old-style function.
* Adding void seems to fix this error:
'this old-style function definition is not preceded by a prototype [-Werror,-Wstrict-prototypes]'

Signed-off-by: Carlo Dee <carlodee.official@proton.me>